### ISSUE TITLE
support for virtualElements

### ISSUE THREAD

**Issue by flasaracina** [code-chris/aurelia-knockout#17]
aurelia-knockout plugin support for virtual elements is buggy.
The `foreach` binding if is written as a virtual element (aka in a comment) doesnt't work properly. You cannot acces the `$data` variable for example.

Thank you

**Comment by ckotzbauer** [comment]
@flasaracina Do you have a small code snippet to reproduce?

**Comment by flasaracina** [comment]
Nvm, It was an aurelia configuration issue. In my  `aurelia_project/tasks/process-markup.js` I had `removeComments: true`.

My bad. Thank you for the fast reply,

**Comment by ckotzbauer** [comment]
no problem ;)
