### ISSUE TITLE
Aurelia not waiting after widgets

### ISSUE THREAD

**Issue by Justin-Lessard** [code-chris/aurelia-knockout#19]
We are in the process of converting a Durandal/knockout project to Aurelia using aurelia-knockout. We changed all references to Durandal widgets (`data-bind="widget: { kind: ...` ") to knockout compose elements (`data-bind="compose: { model: ..."`}).

 It works for most part but our problem is that Aurelia does not wait for the widgets to finish loading before calling the parent page's events.
 
----------
Let's say we have a basic view `welcome.html`

    <template>
      <div knockout>
        <div data-bind="compose: {model: 'widget'}"></div>
      </div>
    </template>

And its viewmodel `welcome.js`

    export class Welcome {
        activate() {
            window.console.log("page:activate");
        }
        attached() {
          window.console.log("page:attached");
        }  
    }
    
----------
And we compose a simple widget inside the page `widget.html`

    <template>
      <div knockout>
          TEST widget
      </div>
    </template>

and the widget viewmodel `widget.js`

    export class test {    
        activate() {
            window.console.log("widget:activate");
        }
        compositionComplete(element, parentElement) {
            window.console.log("widget:compositionComplete");
        }
    }

----------
When we load this page, this is what is printed in the console. The page is attached before the widget is even created.

    page:activate
    page:attached 
    widget:activate
    widget:compositionComplete

Normally, I would expect the lifecycle to be like this

    page:activate
    widget:activate
    widget:compositionComplete
    page:attached 

----------

The page is attached before we started loading the widget. In durandal the page compositionComplete method would only fire once all the widgets renders completed. Is there a way to make Aurelia wait on the knockout compose elements before completing the navigation and calling the attached() on the page viewmodel?

Our other issue is that in durandal, if we returned a promise in a widget activate, the durandal `router.isNavigating` observable would remain true until the promise resolved. However this is not the case using aurelia. It seems aurelia is never waiting for the widget activate promise to complete. Is this normal?

**Comment by ckotzbauer** [comment]
Hi @Zirkonix ,
thanks for your question!

First of all, there are two lifecycles in Aurelia. The [Component Lifecycle](http://aurelia.io/docs/fundamentals/components#the-component-lifecycle) with
- created(...)
- bind(...)
- attached()
- detached()
- unbind()

and the [Router Lifecycle](http://aurelia.io/docs/fundamentals/cheat-sheet#routing) (See "The Route Screen Activation Lifecycle") with
- canActivate(...)
- activate(...)
- canDeactivate(...)
- deactivate(...)

I assume, that your `welcome` view is not accessed via the router. Then there's no `activate` callback you can register on, except the `welcome` view is composed itself. If the `welcome` view is "only" bound via custom-element syntax then there's a `bind` callback instead, which isn't available in case of composition.

Promise return values are supported for `activate` functions in both lifecycles.

There's no `compositionComplete` callback in Aurelia. This plugin calls this functions only to make transition to Aurelia easier. It is invoked if the composition engine has completed its work.

The `attached` callbacks does not guarantee that all subviews are initialized properly, it only confirms that the current view is connected to the DOM sucessfully, so you can start selecting things with JQuery or something else.

Why is it so important for you to ensure that all subviews are loaded?

**Comment by Justin-Lessard** [comment]
Thank you for your fast response!

`welcome` is a normal page and is accessed via the router.

Our main problem is not with attached or compositionComplete, but with the activate callback in the widget. Both activate methods are called on the page (welcome) and on the widget, but Aurelia does not wait for the activate on the widget before completing the navigation (isNavigating false) when using the widget with aurelia-knockout and <div data-bind="compose..."> 

I've made a [repo to reproduce this issue](https://github.com/Zirkonix/aurelia-knockout-activation-issue), and I've updated the test widget to return a promise taking 5 seconds to resolve.

	export class widget {
	  constructor() {
		this.text = ko.observable('Loading...');		
	  }
	  activate() {		
		return new Promise((callback) => {
		  setTimeout(() => {
			this.text("Done");
			callback();
		  }, 5000);
		});
	  }
	}
	
-----

I would expect the navigation to wait 5s before seeing the page since the widget activation is not completed. But instead, it load instantly and I get a blank page for 5s until the widget activation complete.

If I try the exact same thing using a `<compose ..>`, everything works as expected.

You can replace the `<div data-bind="...` line by the `<compose` line in comment in `/src/welcome.html` and it should work.

**Comment by ckotzbauer** [comment]
Thanks for the test project. Aurelia does not wait for child views to be initialized successfully.

You can return promises in the `activate` function and Aurelia would wait on their fullfillment. You can see this if you place a `console.log` in the `attached` function of `testAU`. This log is delayed for 5 seconds, as expected. The reason why the `welcome` view is not "waiting": The `activate` function does not return a promise to wait for. It is "ready" immediately.

I copied the five-second-promise to the `activate` of `welcome` too. Then the navigation completion was delayed too, but the initialization process of `testAU` does not start. So the viewmodel of the parent has to be activated before the initialization of the childs can begin...

If you want to know when your page components are all fully initialized, you cannot use the `navigation:complete` event.

I personally would try then something like a registration mechanism, where all components of a page are registered (at the start of each initialization). At the end of each component initialization the component tells the registry, that it is ready now. If all components which are registered are ready, you can fire an event by yourself with the "aurelia-event-aggregator"...

**Comment by Justin-Lessard** [comment]
The thing is, using the `testAU` in a aurelia compose, it's working as expected. The page wait for the `testAU` activate promise to resolve before firing the attached event.

    page:activate
    testAU:constructor
    testAU:activating
    page:attached
    testAU:attached

However, when I replace the `testAu` aurelia component by a knockout component, in our case `widget`, the page is attached before the widget is created.

    page:activate
    page:attached
    widget:constructor
    widget:activating
    widget:compositionComplete

I understand the children will always be created after the page activation is completed. But I thought the activation of the children were supposed to be completed too before the parent viewmodel could be attached?

**Comment by ckotzbauer** [comment]
I found the reason for this behavior: Some of my code in the knockout-composition module runs async. The main problem is, that the `bind` function from the `knockout` custom attribute cannot return promises and knockout isn't aware of promises too....

So the composition isn't ready yet and aurelia means the `knockout` custom attribute is processed completely.

**Comment by mlessd** [comment]
Do you think this is fixable somehow? We don't know knockout or Aurelia well enough to really understand how this plugin's code works.
Thanks!

**Comment by Justin-Lessard** [comment]
Thank you very much for your answer! 

I feel like I lack the proper knowledge and understanding in in the core framework and its underlying mechanism to fix the issue myself.

Any clue on how/if it's possible to implement a fix for this issue?

**Comment by ckotzbauer** [comment]
I asked the Aurelia folks and looked into the composition code of aurelia. It's almost impossible to do this in sync and knockout is too old to support promises. So there's no fix possible in this plugin unfortunately.

So in your case @Zirkonix I would try to replace the old durandal compositions in html with new aurelia ones. This should be not so hard, cause of the high syntax similarity...

**Comment by ckotzbauer** [comment]
closed for now
