### ISSUE TITLE
Awesome Work

### ISSUE THREAD

**Issue by EisenbergEffect** [code-chris/aurelia-knockout#2]
This looks really nice. Thanks so much for working on this! I'm sure a lot of people will greatly benefit from it. I have a couple of questions for you:
1. Would you be interested in writing a blog post and appearing as a community guest on our official blog?
2. Would you be interested in helping us finish up the Durandal migration guide, perhaps incorporating your plugin as part of the migration process?

Looking forward to hearing from you soon!

**Comment by ckotzbauer** [comment]
@EisenbergEffect  Thanks for your positive reply.

Yes, I can write a blog post about this plugin and how it works. I suppose, that the blog is based on markdown files?

And yes, I can help to finish the migration guide for Durandal using my plugin. Does already exists some small part in docs about this topic or is this completely new? If it's new: Where should I place this document?

**Comment by EisenbergEffect** [comment]
Awesome! For the blog, the format is markdown. Also, for the Durandal docs, we have a preliminary document here: https://github.com/aurelia/framework/blob/master/doc/article/drafts/durandal-to-aurelia.md It's in the framework repo. So, if you want, feel free to just submit a PR with any changes and additions you think would improve the document. When we feel it's ready, we can convert it to the final docs format and launch it in the official docs.

Feel free to cc me here or email me if/when you have a blog post ready too. Make sure to include a little bio so we can introduce you to the community. Include twitter or website as well so we can provide a way for people to contact you for work, etc. if you desire.

**Comment by ckotzbauer** [comment]
Added migration guide to repo wiki: https://github.com/code-chris/aurelia-knockout/wiki
