### ISSUE TITLE
ES6 code in dist

### ISSUE THREAD

**Issue by AStoker** [code-chris/aurelia-knockout#20]
Just noticed this change in 2.0.0, there are classes and ES6 code inside the 2.0.0 release. Was this intentional? It looks like it just wasn't transpiled.

https://github.com/code-chris/aurelia-knockout/blob/70e2381165633db015d1eece6ce54bc873bcc140/dist/amd/knockout-bindable.js#L9

**Comment by ckotzbauer** [comment]
thanks @AStoker. The `tsconfig.json` was not correctly configured. Fixed in 2.0.2
