### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by AStoker** [code-chris/aurelia-knockout#3]
There are some dependencies that need to be updated, and also included.
When trying to run the code with what you suggested, `knockout-composition` is looking for `aurelia-loader` which is not installed as a primary dependency in my project (not installed as a dependency inside `aurelia-knockout`)

**Comment by ckotzbauer** [comment]
Thanks for finding this issue! I've added the three missing aurelia dependencies, so it should work now. 

This was released in 0.2.1
