### ISSUE TITLE
IOS 16 issue

### ISSUE THREAD

**Issue by mteneglio** [code-chris/aurelia-knockout#45]
since the latest update IOS 16
every html page that having the "knockout" custom attribute which surrounds all elements, cannot be loaded anymore, page simply crash

<template>
    <div knockout>
       ......
    </div>
</template>

if someone seeing the same problem ? issue happen with Safari and Chrome in the same way when using the latest IOS 16

IOS 15.7 work perfectly, no issue at all
and no issue with latest version of android
using the latest package aurelia-knockout@2.4.2

**Comment by ckotzbauer** [comment]
Please read my comment here: https://github.com/aurelia-contrib/aurelia-knockout/issues/44#issuecomment-1255980429
This issue is not part of this library and can't be fixed.
