### ISSUE TITLE
Cool project!

### ISSUE THREAD

**Issue by MrChriZ** [code-chris/aurelia-knockout#7]
I just read the bit about Aurelias binding language being flexible and immediately wondered if there was a knockout plugin as someone that's been using Knockout for a few years ...and low and behold here it is.

Please excuse me for creating this as an issue but I just had to comment on what a cool project this was 👍 

:)

**Comment by ckotzbauer** [comment]
Hi @MrChriZ ,
thanks for this very positive feedback!!!
